#version: '3.8'

services:
  # VM1: Agent SNMPv3 DME
  dme_simulator:
    build:
      context: ./vm1_dme_simulator
      dockerfile: Dockerfile
    container_name: rcms_dme_simulator
    restart: unless-stopped
    ports:
      - "161:161/udp"
    volumes:
      - ./logs/dme_simulator:/app/logs
    environment:
      - SNMP_USER=dmeuser
      - SNMP_AUTH_PASSWORD=authpassword
      - SNMP_PRIV_PASSWORD=privpassword
    networks:
      - rcms_network

  # VM2: Client SNMPv3
  data_collector:
    build:
      context: ./vm2_data_collector
      dockerfile: Dockerfile
    container_name: rcms_data_collector
    restart: unless-stopped
    depends_on:
      - dme_simulator
      - logstash
    volumes:
      - ./data:/app/data
      - ./logs/data_collector:/app/logs
    environment:
      - SNMP_HOST=dme_simulator
      - SNMP_PORT=161
      - SNMP_USER=dmeuser
      - SNMP_AUTH_PASSWORD=authpassword
      - SNMP_PRIV_PASSWORD=privpassword
      - COLLECTION_INTERVAL=10
      - OUTPUT_FILE=/app/data/dme_data.csv
      - LOGSTASH_ENABLED=true
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
      - TIMEOUT=5
    networks:
      - rcms_network

  # VM3: Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: rcms_elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_logs:/usr/share/elasticsearch/logs
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=SuperAdmin123!
      - path.logs=/usr/share/elasticsearch/logs
      - bootstrap.memory_lock=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - rcms_network
    healthcheck:
      test: ["CMD", "curl", "-u", "elastic:SuperAdmin123!", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # VM4: Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.0
    container_name: rcms_logstash
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./vm4_logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./vm4_logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - logstash_logs:/var/log/logstash
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=SuperAdmin123!
    networks:
      - rcms_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600/_node"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # VM5: Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: rcms_kibana
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - kibana_logs:/var/log/kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=SuperAdmin123!
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=ChangeMe123456789012345678901234567890
      - XPACK_SECURITY_ENABLED=true
      - SERVER_NAME=rcms-kibana
      - SERVER_HOST=0.0.0.0
      - I18N_LOCALE=fr
    networks:
      - rcms_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

networks:
  rcms_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  elasticsearch_data:
    driver: local
  elasticsearch_logs:
    driver: local
  logstash_logs:
    driver: local
  kibana_logs:
    driver: local
