http.host: "0.0.0.0"
http.port: 9600

path.config: /usr/share/logstash/pipeline
config.reload.automatic: true
config.reload.interval: 3s

pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Désactiver X-Pack monitoring pour simplifier
xpack.monitoring.enabled: false

# Log level pour debug
log.level: info
path.logs: /var/log/logstash
