# Configuration Logstash pour RCMS_Test
# Auteur: Arthur

http.host: "0.0.0.0"
http.port: 9600

# Chemin des logs
path.logs: /var/log/logstash

# Configuration du pipeline
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Configuration de la sécurité
xpack.monitoring.enabled: false

# Configuration du reload automatique
config.reload.automatic: true
config.reload.interval: 3s
